package net.slide.pojo;

// Generated Jun 6, 2012 12:49:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblChklst generated by hbm2java
 */
@Entity
@Table(name = "tbl_chklst", schema = "public")
public class TblChklst implements java.io.Serializable {

	private int chklstId;
	private TblChklstGroup tblChklstGroup;
	private TblChklstTopic tblChklstTopic;
	private String chklstSubject;
	private String chklstContents;
	private String chklstAttachPath;
	private String chklstAttachFilename;
	private String chklstStatus;
	private int chklstOwnerRole;
	private int chklstOwnerSite;
	private Date chklstStartDate;
	private Date chklstEndDate;
	private String updatedBy;
	private Date updatedDate;
	private String chklstAssign;
	private Set<TblChklstStore> tblChklstStores = new HashSet<TblChklstStore>(0);
	private Set<TblChklstDetail> tblChklstDetails = new HashSet<TblChklstDetail>(
			0);
	private Set<TblChklstStoreDetail> tblChklstStoreDetails = new HashSet<TblChklstStoreDetail>(
			0);
	private Set<TblChklstArea> tblChklstAreas = new HashSet<TblChklstArea>(0);
	private Set<TblChklstAreaDetail> tblChklstAreaDetails = new HashSet<TblChklstAreaDetail>(
			0);

	public TblChklst() {
	}

	public TblChklst(int chklstId, TblChklstGroup tblChklstGroup,
			TblChklstTopic tblChklstTopic, int chklstOwnerRole,
			int chklstOwnerSite) {
		this.chklstId = chklstId;
		this.tblChklstGroup = tblChklstGroup;
		this.tblChklstTopic = tblChklstTopic;
		this.chklstOwnerRole = chklstOwnerRole;
		this.chklstOwnerSite = chklstOwnerSite;
	}

	public TblChklst(int chklstId, TblChklstGroup tblChklstGroup,
			TblChklstTopic tblChklstTopic, String chklstSubject,
			String chklstContents, String chklstAttachPath,
			String chklstAttachFilename, String chklstStatus,
			int chklstOwnerRole, int chklstOwnerSite, Date chklstStartDate,
			Date chklstEndDate, String updatedBy, Date updatedDate,
			String chklstAssign, Set<TblChklstStore> tblChklstStores,
			Set<TblChklstDetail> tblChklstDetails,
			Set<TblChklstStoreDetail> tblChklstStoreDetails,
			Set<TblChklstArea> tblChklstAreas,
			Set<TblChklstAreaDetail> tblChklstAreaDetails) {
		this.chklstId = chklstId;
		this.tblChklstGroup = tblChklstGroup;
		this.tblChklstTopic = tblChklstTopic;
		this.chklstSubject = chklstSubject;
		this.chklstContents = chklstContents;
		this.chklstAttachPath = chklstAttachPath;
		this.chklstAttachFilename = chklstAttachFilename;
		this.chklstStatus = chklstStatus;
		this.chklstOwnerRole = chklstOwnerRole;
		this.chklstOwnerSite = chklstOwnerSite;
		this.chklstStartDate = chklstStartDate;
		this.chklstEndDate = chklstEndDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.chklstAssign = chklstAssign;
		this.tblChklstStores = tblChklstStores;
		this.tblChklstDetails = tblChklstDetails;
		this.tblChklstStoreDetails = tblChklstStoreDetails;
		this.tblChklstAreas = tblChklstAreas;
		this.tblChklstAreaDetails = tblChklstAreaDetails;
	}

	@Id
	@Column(name = "chklst_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getChklstId() {
		return this.chklstId;
	}

	public void setChklstId(int chklstId) {
		this.chklstId = chklstId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chklst_group_id", nullable = false)
	public TblChklstGroup getTblChklstGroup() {
		return this.tblChklstGroup;
	}

	public void setTblChklstGroup(TblChklstGroup tblChklstGroup) {
		this.tblChklstGroup = tblChklstGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chklst_topic_id", nullable = false)
	public TblChklstTopic getTblChklstTopic() {
		return this.tblChklstTopic;
	}

	public void setTblChklstTopic(TblChklstTopic tblChklstTopic) {
		this.tblChklstTopic = tblChklstTopic;
	}

	@Column(name = "chklst_subject", length = 100)
	public String getChklstSubject() {
		return this.chklstSubject;
	}

	public void setChklstSubject(String chklstSubject) {
		this.chklstSubject = chklstSubject;
	}

	@Column(name = "chklst_contents", length = 1024)
	public String getChklstContents() {
		return this.chklstContents;
	}

	public void setChklstContents(String chklstContents) {
		this.chklstContents = chklstContents;
	}

	@Column(name = "chklst_attach_path", length = 1024)
	public String getChklstAttachPath() {
		return this.chklstAttachPath;
	}

	public void setChklstAttachPath(String chklstAttachPath) {
		this.chklstAttachPath = chklstAttachPath;
	}

	@Column(name = "chklst_attach_filename", length = 512)
	public String getChklstAttachFilename() {
		return this.chklstAttachFilename;
	}

	public void setChklstAttachFilename(String chklstAttachFilename) {
		this.chklstAttachFilename = chklstAttachFilename;
	}

	@Column(name = "chklst_status", length = 1)
	public String getChklstStatus() {
		return this.chklstStatus;
	}

	public void setChklstStatus(String chklstStatus) {
		this.chklstStatus = chklstStatus;
	}

	@Column(name = "chklst_owner_role", nullable = false)
	public int getChklstOwnerRole() {
		return this.chklstOwnerRole;
	}

	public void setChklstOwnerRole(int chklstOwnerRole) {
		this.chklstOwnerRole = chklstOwnerRole;
	}

	@Column(name = "chklst_owner_site", nullable = false)
	public int getChklstOwnerSite() {
		return this.chklstOwnerSite;
	}

	public void setChklstOwnerSite(int chklstOwnerSite) {
		this.chklstOwnerSite = chklstOwnerSite;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "chklst_start_date", length = 29)
	public Date getChklstStartDate() {
		return this.chklstStartDate;
	}

	public void setChklstStartDate(Date chklstStartDate) {
		this.chklstStartDate = chklstStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "chklst_end_date", length = 29)
	public Date getChklstEndDate() {
		return this.chklstEndDate;
	}

	public void setChklstEndDate(Date chklstEndDate) {
		this.chklstEndDate = chklstEndDate;
	}

	@Column(name = "updated_by", length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "chklst_assign", length = 1)
	public String getChklstAssign() {
		return this.chklstAssign;
	}

	public void setChklstAssign(String chklstAssign) {
		this.chklstAssign = chklstAssign;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblChklst")
	public Set<TblChklstStore> getTblChklstStores() {
		return this.tblChklstStores;
	}

	public void setTblChklstStores(Set<TblChklstStore> tblChklstStores) {
		this.tblChklstStores = tblChklstStores;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblChklst")
	public Set<TblChklstDetail> getTblChklstDetails() {
		return this.tblChklstDetails;
	}

	public void setTblChklstDetails(Set<TblChklstDetail> tblChklstDetails) {
		this.tblChklstDetails = tblChklstDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblChklst")
	public Set<TblChklstStoreDetail> getTblChklstStoreDetails() {
		return this.tblChklstStoreDetails;
	}

	public void setTblChklstStoreDetails(
			Set<TblChklstStoreDetail> tblChklstStoreDetails) {
		this.tblChklstStoreDetails = tblChklstStoreDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblChklst")
	public Set<TblChklstArea> getTblChklstAreas() {
		return this.tblChklstAreas;
	}

	public void setTblChklstAreas(Set<TblChklstArea> tblChklstAreas) {
		this.tblChklstAreas = tblChklstAreas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblChklst")
	public Set<TblChklstAreaDetail> getTblChklstAreaDetails() {
		return this.tblChklstAreaDetails;
	}

	public void setTblChklstAreaDetails(
			Set<TblChklstAreaDetail> tblChklstAreaDetails) {
		this.tblChklstAreaDetails = tblChklstAreaDetails;
	}

}


