package net.slide.pojo;

// Generated Jun 6, 2012 12:49:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblChklstAreaDetail generated by hbm2java
 */
@Entity
@Table(name = "tbl_chklst_area_detail", schema = "public")
public class TblChklstAreaDetail implements java.io.Serializable {

	private int chklstAreaDetailId;
	private TblArea tblArea;
	private TblChklstDetail tblChklstDetail;
	private TblChklst tblChklst;
	private String chklstResponse;
	private String chklstResponseStatus;
	private String updatedBy;
	private Date updatedDate;

	public TblChklstAreaDetail() {
	}

	public TblChklstAreaDetail(int chklstAreaDetailId, TblArea tblArea,
			TblChklstDetail tblChklstDetail, TblChklst tblChklst) {
		this.chklstAreaDetailId = chklstAreaDetailId;
		this.tblArea = tblArea;
		this.tblChklstDetail = tblChklstDetail;
		this.tblChklst = tblChklst;
	}

	public TblChklstAreaDetail(int chklstAreaDetailId, TblArea tblArea,
			TblChklstDetail tblChklstDetail, TblChklst tblChklst,
			String chklstResponse, String chklstResponseStatus,
			String updatedBy, Date updatedDate) {
		this.chklstAreaDetailId = chklstAreaDetailId;
		this.tblArea = tblArea;
		this.tblChklstDetail = tblChklstDetail;
		this.tblChklst = tblChklst;
		this.chklstResponse = chklstResponse;
		this.chklstResponseStatus = chklstResponseStatus;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "chklst_area_detail_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getChklstAreaDetailId() {
		return this.chklstAreaDetailId;
	}

	public void setChklstAreaDetailId(int chklstAreaDetailId) {
		this.chklstAreaDetailId = chklstAreaDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "area_id", nullable = false)
	public TblArea getTblArea() {
		return this.tblArea;
	}

	public void setTblArea(TblArea tblArea) {
		this.tblArea = tblArea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chklst_detail_id", nullable = false)
	public TblChklstDetail getTblChklstDetail() {
		return this.tblChklstDetail;
	}

	public void setTblChklstDetail(TblChklstDetail tblChklstDetail) {
		this.tblChklstDetail = tblChklstDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chklst_id", nullable = false)
	public TblChklst getTblChklst() {
		return this.tblChklst;
	}

	public void setTblChklst(TblChklst tblChklst) {
		this.tblChklst = tblChklst;
	}

	@Column(name = "chklst_response")
	public String getChklstResponse() {
		return this.chklstResponse;
	}

	public void setChklstResponse(String chklstResponse) {
		this.chklstResponse = chklstResponse;
	}

	@Column(name = "chklst_response_status", length = 1)
	public String getChklstResponseStatus() {
		return this.chklstResponseStatus;
	}

	public void setChklstResponseStatus(String chklstResponseStatus) {
		this.chklstResponseStatus = chklstResponseStatus;
	}

	@Column(name = "updated_by", length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
