package net.slide.pojo;

// default package
// Generated Sep 13, 2012 12:40:08 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblPostUpload generated by hbm2java
 */
@Entity
@Table(name = "tbl_post_upload", schema = "public")
public class TblPostUpload implements java.io.Serializable {

	private int id;
	private TblPost tblPost;
	private String postAttachFilename;
	private String postAttachPath;

	public TblPostUpload() {
	}

	public TblPostUpload(int id) {
		this.id = id;
	}

	public TblPostUpload(int id, TblPost tblPost, String postAttachFilename,
			String postAttachPath) {
		this.id = id;
		this.tblPost = tblPost;
		this.postAttachFilename = postAttachFilename;
		this.postAttachPath = postAttachPath;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "post_id")
	public TblPost getTblPost() {
		return this.tblPost;
	}

	public void setTblPost(TblPost tblPost) {
		this.tblPost = tblPost;
	}

	@Column(name = "post_attach_filename", length = 512)
	public String getPostAttachFilename() {
		return this.postAttachFilename;
	}

	public void setPostAttachFilename(String postAttachFilename) {
		this.postAttachFilename = postAttachFilename;
	}

	@Column(name = "post_attach_path", length = 1024)
	public String getPostAttachPath() {
		return this.postAttachPath;
	}

	public void setPostAttachPath(String postAttachPath) {
		this.postAttachPath = postAttachPath;
	}

}
