package net.slide.pojo;

// Generated Jun 18, 2012 7:42:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblStore generated by hbm2java
 */
@Entity
@Table(name = "tbl_store", schema = "public")
public class TblStore implements java.io.Serializable {

	private int storeId;
	private TblBanner tblBanner;
	private TblArea tblArea;
	private TblUser tblUser;
	private String storeCode;
	private String storeLocation;
	private String storeName;
	private String country;
	private String postalCode;
	private String storeAdrLine1;
	private String storeAdrLine2;
	private String storeTelNo;
	private String storeEmailId;
	private String storeFaxNo;
	private String storeStatus;
	private Date updatedDate;
	private String updatedBy;
	private Set<TblPostStore> tblPostStores = new HashSet<TblPostStore>(0);
	private Set<TblChklstStoreDetail> tblChklstStoreDetails = new HashSet<TblChklstStoreDetail>(
			0);
	private Set<TblTaskStore> tblTaskStores = new HashSet<TblTaskStore>(0);
	private Set<TblChklstStore> tblChklstStores = new HashSet<TblChklstStore>(0);

	public TblStore() {
	}

	public TblStore(int storeId, TblBanner tblBanner, TblArea tblArea,
			String storeCode) {
		this.storeId = storeId;
		this.tblBanner = tblBanner;
		this.tblArea = tblArea;
		this.storeCode = storeCode;
	}

	public TblStore(int storeId, TblBanner tblBanner, TblArea tblArea,
			TblUser tblUser, String storeCode, String storeLocation,
			String storeName, String country, String postalCode,
			String storeAdrLine1, String storeAdrLine2, String storeTelNo,
			String storeEmailId, String storeFaxNo, String storeStatus,
			Date updatedDate, String updatedBy,
			Set<TblPostStore> tblPostStores,
			Set<TblChklstStoreDetail> tblChklstStoreDetails,
			Set<TblTaskStore> tblTaskStores, Set<TblChklstStore> tblChklstStores) {
		this.storeId = storeId;
		this.tblBanner = tblBanner;
		this.tblArea = tblArea;
		this.tblUser = tblUser;
		this.storeCode = storeCode;
		this.storeLocation = storeLocation;
		this.storeName = storeName;
		this.country = country;
		this.postalCode = postalCode;
		this.storeAdrLine1 = storeAdrLine1;
		this.storeAdrLine2 = storeAdrLine2;
		this.storeTelNo = storeTelNo;
		this.storeEmailId = storeEmailId;
		this.storeFaxNo = storeFaxNo;
		this.storeStatus = storeStatus;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
		this.tblPostStores = tblPostStores;
		this.tblChklstStoreDetails = tblChklstStoreDetails;
		this.tblTaskStores = tblTaskStores;
		this.tblChklstStores = tblChklstStores;
	}

	@Id
	@Column(name = "store_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getStoreId() {
		return this.storeId;
	}

	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "banner_id", nullable = false)
	public TblBanner getTblBanner() {
		return this.tblBanner;
	}

	public void setTblBanner(TblBanner tblBanner) {
		this.tblBanner = tblBanner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "area_id", nullable = false)
	public TblArea getTblArea() {
		return this.tblArea;
	}

	public void setTblArea(TblArea tblArea) {
		this.tblArea = tblArea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_manager_id")
	public TblUser getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(TblUser tblUser) {
		this.tblUser = tblUser;
	}

	@Column(name = "store_code", nullable = false, length = 25)
	public String getStoreCode() {
		return this.storeCode;
	}

	public void setStoreCode(String storeCode) {
		this.storeCode = storeCode;
	}

	@Column(name = "store_location", length = 100)
	public String getStoreLocation() {
		return this.storeLocation;
	}

	public void setStoreLocation(String storeLocation) {
		this.storeLocation = storeLocation;
	}

	@Column(name = "store_name", length = 100)
	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	@Column(name = "country", length = 25)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "postal_code", length = 10)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "store_adr_line_1")
	public String getStoreAdrLine1() {
		return this.storeAdrLine1;
	}

	public void setStoreAdrLine1(String storeAdrLine1) {
		this.storeAdrLine1 = storeAdrLine1;
	}

	@Column(name = "store_adr_line_2")
	public String getStoreAdrLine2() {
		return this.storeAdrLine2;
	}

	public void setStoreAdrLine2(String storeAdrLine2) {
		this.storeAdrLine2 = storeAdrLine2;
	}

	@Column(name = "store_tel_no", length = 50)
	public String getStoreTelNo() {
		return this.storeTelNo;
	}

	public void setStoreTelNo(String storeTelNo) {
		this.storeTelNo = storeTelNo;
	}

	@Column(name = "store_email_id", length = 50)
	public String getStoreEmailId() {
		return this.storeEmailId;
	}

	public void setStoreEmailId(String storeEmailId) {
		this.storeEmailId = storeEmailId;
	}

	@Column(name = "store_fax_no", length = 50)
	public String getStoreFaxNo() {
		return this.storeFaxNo;
	}

	public void setStoreFaxNo(String storeFaxNo) {
		this.storeFaxNo = storeFaxNo;
	}

	@Column(name = "store_status", length = 1)
	public String getStoreStatus() {
		return this.storeStatus;
	}

	public void setStoreStatus(String storeStatus) {
		this.storeStatus = storeStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "updated_by", length = 20)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblStore")
	public Set<TblPostStore> getTblPostStores() {
		return this.tblPostStores;
	}

	public void setTblPostStores(Set<TblPostStore> tblPostStores) {
		this.tblPostStores = tblPostStores;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblStore")
	public Set<TblChklstStoreDetail> getTblChklstStoreDetails() {
		return this.tblChklstStoreDetails;
	}

	public void setTblChklstStoreDetails(
			Set<TblChklstStoreDetail> tblChklstStoreDetails) {
		this.tblChklstStoreDetails = tblChklstStoreDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblStore")
	public Set<TblTaskStore> getTblTaskStores() {
		return this.tblTaskStores;
	}

	public void setTblTaskStores(Set<TblTaskStore> tblTaskStores) {
		this.tblTaskStores = tblTaskStores;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblStore")
	public Set<TblChklstStore> getTblChklstStores() {
		return this.tblChklstStores;
	}

	public void setTblChklstStores(Set<TblChklstStore> tblChklstStores) {
		this.tblChklstStores = tblChklstStores;
	}

}
