package net.slide.pojo;

// Generated Jun 18, 2012 7:42:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblTaskArea generated by hbm2java
 */
@Entity
@Table(name = "tbl_task_area", schema = "public")
public class TblTaskArea implements java.io.Serializable {

	private int taskAreaId;
	private TblArea tblArea;
	private TblTask tblTask;
	private String taskStatus;
	private String taskResponse;
	private String taskRemark;
	private String updatedBy;
	private Date updatedDate;
	private Set<TblTaskResponseArea> tblTaskResponses = new HashSet<TblTaskResponseArea>(0);
        
         //added by hafizd on January 21st 2014
        
//        private String taskProofPath;
//	private String taskProofFilename;

        //end added

	public TblTaskArea() {
	}

	public TblTaskArea(int taskAreaId, TblArea tblArea, TblTask tblTask) {
		this.taskAreaId = taskAreaId;
		this.tblArea = tblArea;
		this.tblTask = tblTask;
	}

	public TblTaskArea(int taskAreaId, TblArea tblArea, TblTask tblTask,
			String taskStatus, String taskResponse, String taskRemark,
			String updatedBy, Date updatedDate,
                        Set<TblTaskResponseArea> tblTaskResponses) {
		this.taskAreaId = taskAreaId;
		this.tblArea = tblArea;
		this.tblTask = tblTask;
		this.taskStatus = taskStatus;
		this.taskResponse = taskResponse;
		this.taskRemark = taskRemark;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
                this.tblTaskResponses = tblTaskResponses;
                
//                this.taskProofPath = taskProofPath;
//                this.taskProofFilename = taskProofFilename;
	}

	@Id
	@Column(name = "task_area_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getTaskAreaId() {
		return this.taskAreaId;
	}

	public void setTaskAreaId(int taskAreaId) {
		this.taskAreaId = taskAreaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "area_id", nullable = false)
	public TblArea getTblArea() {
		return this.tblArea;
	}

	public void setTblArea(TblArea tblArea) {
		this.tblArea = tblArea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "task_id", nullable = false)
	public TblTask getTblTask() {
		return this.tblTask;
	}

	public void setTblTask(TblTask tblTask) {
		this.tblTask = tblTask;
	}

	@Column(name = "task_status", length = 1)
	public String getTaskStatus() {
		return this.taskStatus;
	}

	public void setTaskStatus(String taskStatus) {
		this.taskStatus = taskStatus;
	}

	@Column(name = "task_response", length = 1)
	public String getTaskResponse() {
		return this.taskResponse;
	}

	public void setTaskResponse(String taskResponse) {
		this.taskResponse = taskResponse;
	}

	@Column(name = "task_remark")
	public String getTaskRemark() {
		return this.taskRemark;
	}

	public void setTaskRemark(String taskRemark) {
		this.taskRemark = taskRemark;
	}

	@Column(name = "updated_by", length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
        
        //added by hafizd on January 21st 2014
        
 /*       @Column(name = "task_proof_path", length = 1024)
	public String getTaskProofPath() {
		return this.taskProofPath;
	}

	public void setTaskProofPath(String taskProofPath) {
		this.taskProofPath = taskProofPath;
	}

	@Column(name = "task_proof_filename", length = 512)
	public String getTaskProofFilename() {
		return this.taskProofFilename;
	}

	public void setTaskProofFilename(String taskProofFilename) {
		this.taskProofFilename = taskProofFilename;
	}
   */     
        //end added
        
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblTaskArea")
	public Set<TblTaskResponseArea> getTblTaskResponses() {
		return this.tblTaskResponses;
	}

	public void setTblTaskResponses(Set<TblTaskResponseArea> tblTaskResponses) {
		this.tblTaskResponses = tblTaskResponses;
	}
        

}
