package net.slide.pojo;

// Generated Jun 18, 2012 7:42:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblTaskStore generated by hbm2java
 */
@Entity
@Table(name = "tbl_task_store", schema = "public")
public class TblTaskStore implements java.io.Serializable {

	private int taskStoreId;
	private TblTask tblTask;
	private TblStore tblStore;
	private String taskStatus;
	private String taskResponse;
	private String taskRemark;
	private String updatedBy;
	private Date updatedDate;
	private Set<TblTaskResponse> tblTaskResponses = new HashSet<TblTaskResponse>(0);
        
        //added by hafizd on January 21st 2014
        
//        private String taskProofPath;
//	private String taskProofFilename;

        //end added

	public TblTaskStore() {
	}

	public TblTaskStore(int taskStoreId, TblTask tblTask, TblStore tblStore) {
		this.taskStoreId = taskStoreId;
		this.tblTask = tblTask;
		this.tblStore = tblStore;
	}

	public TblTaskStore(int taskStoreId, TblTask tblTask, TblStore tblStore,
			String taskStatus, String taskResponse, String taskRemark,
			String updatedBy, Date updatedDate,
                        Set<TblTaskResponse> tblTaskResponses) {
		this.taskStoreId = taskStoreId;
		this.tblTask = tblTask;
		this.tblStore = tblStore;
		this.taskStatus = taskStatus;
		this.taskResponse = taskResponse;
		this.taskRemark = taskRemark;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
//                this.taskProofPath = taskProofPath;
//                this.taskProofFilename = taskProofFilename;
                this.tblTaskResponses = tblTaskResponses;
	}

	@Id
	@Column(name = "task_store_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getTaskStoreId() {
		return this.taskStoreId;
	}

	public void setTaskStoreId(int taskStoreId) {
		this.taskStoreId = taskStoreId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "task_id", nullable = false)
	public TblTask getTblTask() {
		return this.tblTask;
	}

	public void setTblTask(TblTask tblTask) {
		this.tblTask = tblTask;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id", nullable = false)
	public TblStore getTblStore() {
		return this.tblStore;
	}

	public void setTblStore(TblStore tblStore) {
		this.tblStore = tblStore;
	}

	@Column(name = "task_status", length = 1)
	public String getTaskStatus() {
		return this.taskStatus;
	}

	public void setTaskStatus(String taskStatus) {
		this.taskStatus = taskStatus;
	}

	@Column(name = "task_response", length = 1)
	public String getTaskResponse() {
		return this.taskResponse;
	}

	public void setTaskResponse(String taskResponse) {
		this.taskResponse = taskResponse;
	}

	@Column(name = "task_remark")
	public String getTaskRemark() {
		return this.taskRemark;
	}

	public void setTaskRemark(String taskRemark) {
		this.taskRemark = taskRemark;
	}

	@Column(name = "updated_by", length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
        
        //added by hafizd on January 21st 2014
        
/*        @Column(name = "task_proof_path", length = 1024)
	public String getTaskProofPath() {
		return this.taskProofPath;
	}

	public void setTaskProofPath(String taskProofPath) {
		this.taskProofPath = taskProofPath;
	}

	@Column(name = "task_proof_filename", length = 512)
	public String getTaskProofFilename() {
		return this.taskProofFilename;
	}

	public void setTaskProofFilename(String taskProofFilename) {
		this.taskProofFilename = taskProofFilename;
	}
        //end added

*/      
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblTaskStore")
	public Set<TblTaskResponse> getTblTaskResponses() {
		return this.tblTaskResponses;
	}

	public void setTblTaskResponses(Set<TblTaskResponse> tblTaskResponses) {
		this.tblTaskResponses = tblTaskResponses;
	}
        

}
