package net.slide.pojo;

// default package
// Generated Sep 14, 2012 6:12:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblTaskUpload generated by hbm2java
 */
@Entity
@Table(name = "tbl_task_upload", schema = "public")
public class TblTaskUpload implements java.io.Serializable {

	private int id;
	private TblTask tblTask;
	private String taskAttachPath;
	private String taskAttachFilename;
        
        //added by hafizd on January 21st 2014
        
    private String taskApprovePath;
	private String taskApproveFilename;

        //end added
        
	public TblTaskUpload() {
	}

	public TblTaskUpload(int id) {
		this.id = id;
	}

	/*public TblTaskUpload(int id, TblTask tblTask, String taskAttachPath,
			String taskAttachFilename) {*/
        
        // added new class of TblTaskUpload
        
        public TblTaskUpload(int id, TblTask tblTask, String taskAttachPath,
			String taskAttachFilename,String taskApprovePath,
			String taskApproveFilename) {
            
		this.id = id;
		this.tblTask = tblTask;
		this.taskAttachPath = taskAttachPath;
		this.taskAttachFilename = taskAttachFilename;
                this.taskApprovePath = taskApprovePath;
		this.taskApproveFilename = taskApproveFilename;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "task_id")
	public TblTask getTblTask() {
		return this.tblTask;
	}

	public void setTblTask(TblTask tblTask) {
		this.tblTask = tblTask;
	}

	@Column(name = "task_attach_path", length = 1024)
	public String getTaskAttachPath() {
		return this.taskAttachPath;
	}

	public void setTaskAttachPath(String taskAttachPath) {
		this.taskAttachPath = taskAttachPath;
	}

	@Column(name = "task_attach_filename", length = 512)
	public String getTaskAttachFilename() {
		return this.taskAttachFilename;
	}

	public void setTaskAttachFilename(String taskAttachFilename) {
		this.taskAttachFilename = taskAttachFilename;
	}
        
        //added by hafizd on January 21st 2014
        
        @Column(name = "task_approve_path", length = 1024)
	public String getTaskApprovePath() {
		return this.taskApprovePath;
	}

	public void setTaskApprovePath(String taskApprovePath) {
		this.taskApprovePath = taskApprovePath;
	}

	@Column(name = "task_approve_filename", length = 512)
	public String getTaskApproveFilename() {
		return this.taskApproveFilename;
	}

	public void setTaskApproveFilename(String taskApproveFilename) {
		this.taskApproveFilename = taskApproveFilename;
	}
        
        //end added
}
