package net.slide.pojo;

// default package
// Generated Sep 4, 2012 10:19:51 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblGrade generated by hbm2java
 */
@Entity
@Table(name = "tbl_grade", schema = "public")
public class TblGrade implements java.io.Serializable {

	private int gradeId;
	private String gradeName;
	private String gradeValue;

	public TblGrade() {
	}

	public TblGrade(int gradeId) {
		this.gradeId = gradeId;
	}

	public TblGrade(int gradeId, String gradeName, String gradeValue) {
		this.gradeId = gradeId;
		this.gradeName = gradeName;
		this.gradeValue = gradeValue;
	}

	@Id
	@Column(name = "grade_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getGradeId() {
		return this.gradeId;
	}

	public void setGradeId(int gradeId) {
		this.gradeId = gradeId;
	}

	@Column(name = "grade_name", length = 100)
	public String getGradeName() {
		return gradeName;
	}
	
	public void setGradeName(String gradeName) {
		this.gradeName = gradeName;
	}

	
	
	@Column(name = "grade_value", length = 10)
	public String getGradeValue() {
		return this.gradeValue;
	}
	public void setGradeValue(String gradeValue) {
		this.gradeValue = gradeValue;
	}
	

	

}
