package net.slide.pojo;

// Generated Jun 18, 2012 7:42:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblPostArea generated by hbm2java
 */
@Entity
@Table(name = "tbl_post_area", schema = "public")
public class TblPostArea implements java.io.Serializable {

	private int postAreaId;
	private TblArea tblArea;
	private TblPost tblPost;
	private String postStatus;
	private String postRemark;
	private String updatedBy;
	private Date updatedDate;

	public TblPostArea() {
	}

	public TblPostArea(int postAreaId, TblArea tblArea, TblPost tblPost) {
		this.postAreaId = postAreaId;
		this.tblArea = tblArea;
		this.tblPost = tblPost;
	}

	public TblPostArea(int postAreaId, TblArea tblArea, TblPost tblPost,
			String postStatus, String postRemark, String updatedBy,
			Date updatedDate) {
		this.postAreaId = postAreaId;
		this.tblArea = tblArea;
		this.tblPost = tblPost;
		this.postStatus = postStatus;
		this.postRemark = postRemark;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "post_area_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getPostAreaId() {
		return this.postAreaId;
	}

	public void setPostAreaId(int postAreaId) {
		this.postAreaId = postAreaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "area_id", nullable = false)
	public TblArea getTblArea() {
		return this.tblArea;
	}

	public void setTblArea(TblArea tblArea) {
		this.tblArea = tblArea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "post_id", nullable = false)
	public TblPost getTblPost() {
		return this.tblPost;
	}

	public void setTblPost(TblPost tblPost) {
		this.tblPost = tblPost;
	}

	@Column(name = "post_status", length = 1)
	public String getPostStatus() {
		return this.postStatus;
	}

	public void setPostStatus(String postStatus) {
		this.postStatus = postStatus;
	}

	@Column(name = "post_remark")
	public String getPostRemark() {
		return this.postRemark;
	}

	public void setPostRemark(String postRemark) {
		this.postRemark = postRemark;
	}

	@Column(name = "updated_by", length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
