package net.slide.pojo;

// Generated Jun 18, 2012 7:42:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblPost generated by hbm2java
 */
@Entity
@Table(name = "tbl_post", schema = "public")
public class TblPost implements java.io.Serializable {

	private int postId;
	private TblPostTopic tblPostTopic;
	private TblPostForum tblPostForum;
	private String postSubject;
	private String postContents;
	private String postAttachPath;
	private String postAttachFilename;
	private String postStatus;
	private int postOwnerRole;
	private int postOwnerSite;
	private Date postDate;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private Set<TblPostArea> tblPostAreas = new HashSet<TblPostArea>(0);
	private Set<TblPostStore> tblPostStores = new HashSet<TblPostStore>(0);
	private Set<TblPostUpload> tblPostUploads = new HashSet<TblPostUpload>(0);

	public TblPost() {
	}

	public TblPost(int postId, TblPostTopic tblPostTopic,
			TblPostForum tblPostForum, int postOwnerRole, int postOwnerSite) {
		this.postId = postId;
		this.tblPostTopic = tblPostTopic;
		this.tblPostForum = tblPostForum;
		this.postOwnerRole = postOwnerRole;
		this.postOwnerSite = postOwnerSite;
	}

	public TblPost(int postId, TblPostTopic tblPostTopic,
			TblPostForum tblPostForum, String postSubject, String postContents,
			String postAttachPath, String postAttachFilename,
			String postStatus, int postOwnerRole, int postOwnerSite,
			Date postDate, String createdBy, Date createdDate,
			String updatedBy, Date updatedDate, Set<TblPostArea> tblPostAreas,
			Set<TblPostStore> tblPostStores, Set<TblPostUpload> tblPostUploads) {
		this.postId = postId;
		this.tblPostTopic = tblPostTopic;
		this.tblPostForum = tblPostForum;
		this.postSubject = postSubject;
		this.postContents = postContents;
		this.postAttachPath = postAttachPath;
		this.postAttachFilename = postAttachFilename;
		this.postStatus = postStatus;
		this.postOwnerRole = postOwnerRole;
		this.postOwnerSite = postOwnerSite;
		this.postDate = postDate;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.tblPostAreas = tblPostAreas;
		this.tblPostStores = tblPostStores;
		this.tblPostUploads = tblPostUploads;
	}

	@Id
	@Column(name = "post_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getPostId() {
		return this.postId;
	}

	public void setPostId(int postId) {
		this.postId = postId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "topic_id", nullable = false)
	public TblPostTopic getTblPostTopic() {
		return this.tblPostTopic;
	}

	public void setTblPostTopic(TblPostTopic tblPostTopic) {
		this.tblPostTopic = tblPostTopic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "forum_id", nullable = false)
	public TblPostForum getTblPostForum() {
		return this.tblPostForum;
	}

	public void setTblPostForum(TblPostForum tblPostForum) {
		this.tblPostForum = tblPostForum;
	}

	@Column(name = "post_subject", length = 100)
	public String getPostSubject() {
		return this.postSubject;
	}

	public void setPostSubject(String postSubject) {
		this.postSubject = postSubject;
	}

	@Column(name = "post_contents", length = 1024)
	public String getPostContents() {
		return this.postContents;
	}

	public void setPostContents(String postContents) {
		this.postContents = postContents;
	}

	@Column(name = "post_attach_path", length = 1024)
	public String getPostAttachPath() {
		return this.postAttachPath;
	}

	public void setPostAttachPath(String postAttachPath) {
		this.postAttachPath = postAttachPath;
	}

	@Column(name = "post_attach_filename", length = 512)
	public String getPostAttachFilename() {
		return this.postAttachFilename;
	}

	public void setPostAttachFilename(String postAttachFilename) {
		this.postAttachFilename = postAttachFilename;
	}

	@Column(name = "post_status", length = 1)
	public String getPostStatus() {
		return this.postStatus;
	}

	public void setPostStatus(String postStatus) {
		this.postStatus = postStatus;
	}

	@Column(name = "post_owner_role", nullable = false)
	public int getPostOwnerRole() {
		return this.postOwnerRole;
	}

	public void setPostOwnerRole(int postOwnerRole) {
		this.postOwnerRole = postOwnerRole;
	}

	@Column(name = "post_owner_site", nullable = false)
	public int getPostOwnerSite() {
		return this.postOwnerSite;
	}

	public void setPostOwnerSite(int postOwnerSite) {
		this.postOwnerSite = postOwnerSite;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "post_date", length = 29)
	public Date getPostDate() {
		return this.postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

	@Column(name = "created_by", length = 30)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblPost")
	public Set<TblPostArea> getTblPostAreas() {
		return this.tblPostAreas;
	}

	public void setTblPostAreas(Set<TblPostArea> tblPostAreas) {
		this.tblPostAreas = tblPostAreas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblPost")
	public Set<TblPostStore> getTblPostStores() {
		return this.tblPostStores;
	}

	public void setTblPostStores(Set<TblPostStore> tblPostStores) {
		this.tblPostStores = tblPostStores;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblPost")
	public Set<TblPostUpload> getTblPostUploads() {
		return this.tblPostUploads;
	}

	public void setTblPostUploads(Set<TblPostUpload> tblPostUploads) {
		this.tblPostUploads = tblPostUploads;
	}

}
