package net.slide.pojo;

// Generated Jun 18, 2012 7:42:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblUserGrpDtl generated by hbm2java
 */
@Entity
@Table(name = "tbl_user_grp_dtl", schema = "public")
public class TblUserGrpDtl implements java.io.Serializable {

	private TblUserGrpDtlId id;
	private int grpDtlId;
	private String updatedBy;
	private Date updatedDate;

	public TblUserGrpDtl() {
	}

	public TblUserGrpDtl(TblUserGrpDtlId id, int grpDtlId) {
		this.id = id;
		this.grpDtlId = grpDtlId;
	}

	public TblUserGrpDtl(TblUserGrpDtlId id, int grpDtlId, String updatedBy,
			Date updatedDate) {
		this.id = id;
		this.grpDtlId = grpDtlId;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "groupId", column = @Column(name = "group_id", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)) })
	public TblUserGrpDtlId getId() {
		return this.id;
	}

	public void setId(TblUserGrpDtlId id) {
		this.id = id;
	}

	@Column(name = "grp_dtl_id", nullable = false)
	public int getGrpDtlId() {
		return this.grpDtlId;
	}

	public void setGrpDtlId(int grpDtlId) {
		this.grpDtlId = grpDtlId;
	}

	@Column(name = "updated_by", length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
