package net.slide.pojo;

// Generated Jun 18, 2012 7:42:08 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblUserGrpDtlId generated by hbm2java
 */
@Embeddable
public class TblUserGrpDtlId implements java.io.Serializable {

	private int groupId;
	private int userId;

	public TblUserGrpDtlId() {
	}

	public TblUserGrpDtlId(int groupId, int userId) {
		this.groupId = groupId;
		this.userId = userId;
	}

	@Column(name = "group_id", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblUserGrpDtlId))
			return false;
		TblUserGrpDtlId castOther = (TblUserGrpDtlId) other;

		return (this.getGroupId() == castOther.getGroupId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
