package net.slide.pojo;

// Generated Jun 6, 2012 12:49:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblChklstStoreDetail generated by hbm2java
 */
@Entity
@Table(name = "tbl_chklst_store_detail", schema = "public")
public class TblChklstStoreDetail implements java.io.Serializable {

	private int chklstStoreDetailId;
	private TblChklstDetail tblChklstDetail;
	private TblChklst tblChklst;
	private TblStore tblStore;
	private String chklstResponse;
	private String chklstResponseStatus;
	private String chklstResponseSm;
	private String updatedBy;
	private Date updatedDate;

	public TblChklstStoreDetail() {
	}

	public TblChklstStoreDetail(int chklstStoreDetailId,
			TblChklstDetail tblChklstDetail, TblChklst tblChklst,
			TblStore tblStore) {
		this.chklstStoreDetailId = chklstStoreDetailId;
		this.tblChklstDetail = tblChklstDetail;
		this.tblChklst = tblChklst;
		this.tblStore = tblStore;
	}

	public TblChklstStoreDetail(int chklstStoreDetailId,
			TblChklstDetail tblChklstDetail, TblChklst tblChklst,
			TblStore tblStore, String chklstResponse,
			String chklstResponseStatus, String updatedBy, Date updatedDate,String chklstResponseSm) {
		this.chklstStoreDetailId = chklstStoreDetailId;
		this.tblChklstDetail = tblChklstDetail;
		this.tblChklst = tblChklst;
		this.tblStore = tblStore;
		this.chklstResponse = chklstResponse;
		this.chklstResponseStatus = chklstResponseStatus;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.chklstResponseSm=chklstResponseSm;
	}

	@Id
	@Column(name = "chklst_store_detail_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getChklstStoreDetailId() {
		return this.chklstStoreDetailId;
	}

	public void setChklstStoreDetailId(int chklstStoreDetailId) {
		this.chklstStoreDetailId = chklstStoreDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chklst_detail_id", nullable = false)
	public TblChklstDetail getTblChklstDetail() {
		return this.tblChklstDetail;
	}

	public void setTblChklstDetail(TblChklstDetail tblChklstDetail) {
		this.tblChklstDetail = tblChklstDetail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chklst_id", nullable = false)
	public TblChklst getTblChklst() {
		return this.tblChklst;
	}

	public void setTblChklst(TblChklst tblChklst) {
		this.tblChklst = tblChklst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id", nullable = false)
	public TblStore getTblStore() {
		return this.tblStore;
	}

	public void setTblStore(TblStore tblStore) {
		this.tblStore = tblStore;
	}

	@Column(name = "chklst_response")
	public String getChklstResponse() {
		return this.chklstResponse;
	}

	public void setChklstResponse(String chklstResponse) {
		this.chklstResponse = chklstResponse;
	}

	
	
	@Column(name = "chklst_response_status", length = 1)
	public String getChklstResponseStatus() {
		return this.chklstResponseStatus;
	}

	public void setChklstResponseStatus(String chklstResponseStatus) {
		this.chklstResponseStatus = chklstResponseStatus;
	}

	@Column(name = "updated_by", length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	@Column(name = "chklst_response_sm")
	public String getChklstResponseSm() {
		return chklstResponseSm;
	}

	public void setChklstResponseSm(String chklstResponseSm) {
		this.chklstResponseSm = chklstResponseSm;
	}
	
	

}
