package net.slide.pojo;

// Generated Jun 6, 2012 12:49:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblChklstDetail generated by hbm2java
 */
@Entity
@Table(name = "tbl_chklst_detail", schema = "public")
public class TblChklstDetail implements java.io.Serializable {

	private int chklstDetailId;
	private TblChklst tblChklst;
	private String chklstValue;
	private String updatedBy;
	private Date updatedDate;
	private Set<TblChklstAreaDetail> tblChklstAreaDetails = new HashSet<TblChklstAreaDetail>(
			0);
	private Set<TblChklstStoreDetail> tblChklstStoreDetails = new HashSet<TblChklstStoreDetail>(
			0);

	public TblChklstDetail() {
	}

	public TblChklstDetail(int chklstDetailId, TblChklst tblChklst) {
		this.chklstDetailId = chklstDetailId;
		this.tblChklst = tblChklst;
	}

	public TblChklstDetail(int chklstDetailId, TblChklst tblChklst,
			String chklstValue, String updatedBy, Date updatedDate,
			Set<TblChklstAreaDetail> tblChklstAreaDetails,
			Set<TblChklstStoreDetail> tblChklstStoreDetails) {
		this.chklstDetailId = chklstDetailId;
		this.tblChklst = tblChklst;
		this.chklstValue = chklstValue;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.tblChklstAreaDetails = tblChklstAreaDetails;
		this.tblChklstStoreDetails = tblChklstStoreDetails;
	}

	@Id
	@Column(name = "chklst_detail_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getChklstDetailId() {
		return this.chklstDetailId;
	}

	public void setChklstDetailId(int chklstDetailId) {
		this.chklstDetailId = chklstDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chklst_id", nullable = false)
	public TblChklst getTblChklst() {
		return this.tblChklst;
	}

	public void setTblChklst(TblChklst tblChklst) {
		this.tblChklst = tblChklst;
	}

	@Column(name = "chklst_value", length = 1024)
	public String getChklstValue() {
		return this.chklstValue;
	}

	public void setChklstValue(String chklstValue) {
		this.chklstValue = chklstValue;
	}

	@Column(name = "updated_by", length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblChklstDetail")
	public Set<TblChklstAreaDetail> getTblChklstAreaDetails() {
		return this.tblChklstAreaDetails;
	}

	public void setTblChklstAreaDetails(
			Set<TblChklstAreaDetail> tblChklstAreaDetails) {
		this.tblChklstAreaDetails = tblChklstAreaDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblChklstDetail")
	public Set<TblChklstStoreDetail> getTblChklstStoreDetails() {
		return this.tblChklstStoreDetails;
	}

	public void setTblChklstStoreDetails(
			Set<TblChklstStoreDetail> tblChklstStoreDetails) {
		this.tblChklstStoreDetails = tblChklstStoreDetails;
	}

}
