package net.slide.pojo;

// Generated Jun 6, 2012 12:49:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblChklstTopic generated by hbm2java
 */
@Entity
@Table(name = "tbl_chklst_topic", schema = "public")
public class TblChklstTopic implements java.io.Serializable {

	private int topicId;
	private TblChklstGroup tblChklstGroup;
	private TblChklstTemplate tblChklstTemplate;
	private String topicName;
	private String topicStatus;
	private String updatedBy;
	private Date updatedDate;
	private Set<TblChklst> tblChklsts = new HashSet<TblChklst>(0);

	public TblChklstTopic() {
	}

	public TblChklstTopic(int topicId, TblChklstGroup tblChklstGroup,
			TblChklstTemplate tblChklstTemplate) {
		this.topicId = topicId;
		this.tblChklstGroup = tblChklstGroup;
		this.tblChklstTemplate = tblChklstTemplate;
	}

	public TblChklstTopic(int topicId, TblChklstGroup tblChklstGroup,
			TblChklstTemplate tblChklstTemplate, String topicName,
			String topicStatus, String updatedBy, Date updatedDate,
			Set<TblChklst> tblChklsts) {
		this.topicId = topicId;
		this.tblChklstGroup = tblChklstGroup;
		this.tblChklstTemplate = tblChklstTemplate;
		this.topicName = topicName;
		this.topicStatus = topicStatus;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.tblChklsts = tblChklsts;
	}

	@Id
	@Column(name = "topic_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getTopicId() {
		return this.topicId;
	}

	public void setTopicId(int topicId) {
		this.topicId = topicId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chklst_group_id", nullable = false)
	public TblChklstGroup getTblChklstGroup() {
		return this.tblChklstGroup;
	}

	public void setTblChklstGroup(TblChklstGroup tblChklstGroup) {
		this.tblChklstGroup = tblChklstGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "template_id", nullable = false)
	public TblChklstTemplate getTblChklstTemplate() {
		return this.tblChklstTemplate;
	}

	public void setTblChklstTemplate(TblChklstTemplate tblChklstTemplate) {
		this.tblChklstTemplate = tblChklstTemplate;
	}

	@Column(name = "topic_name", length = 100)
	public String getTopicName() {
		return this.topicName;
	}

	public void setTopicName(String topicName) {
		this.topicName = topicName;
	}

	@Column(name = "topic_status", length = 1)
	public String getTopicStatus() {
		return this.topicStatus;
	}

	public void setTopicStatus(String topicStatus) {
		this.topicStatus = topicStatus;
	}

	@Column(name = "updated_by", length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblChklstTopic")
	public Set<TblChklst> getTblChklsts() {
		return this.tblChklsts;
	}

	public void setTblChklsts(Set<TblChklst> tblChklsts) {
		this.tblChklsts = tblChklsts;
	}

}
