package net.slide.pojo;

// Generated Jun 8, 2012 9:43:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblPostStore generated by hbm2java
 */
@Entity
@Table(name = "tbl_post_store", schema = "public")
public class TblPostStore implements java.io.Serializable {

	private int postStoreId;
	private TblPost tblPost;
	private TblStore tblStore;
	private String postStatus;
	private String postRemark;
	private String updatedBy;
	private Date updatedDate;

	public TblPostStore() {
	}

	public TblPostStore(int postStoreId, TblPost tblPost, TblStore tblStore) {
		this.postStoreId = postStoreId;
		this.tblPost = tblPost;
		this.tblStore = tblStore;
	}

	public TblPostStore(int postStoreId, TblPost tblPost, TblStore tblStore,
			String postStatus, String postRemark, String updatedBy,
			Date updatedDate) {
		this.postStoreId = postStoreId;
		this.tblPost = tblPost;
		this.tblStore = tblStore;
		this.postStatus = postStatus;
		this.postRemark = postRemark;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "post_store_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getPostStoreId() {
		return this.postStoreId;
	}

	public void setPostStoreId(int postStoreId) {
		this.postStoreId = postStoreId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "post_id", nullable = false)
	public TblPost getTblPost() {
		return this.tblPost;
	}

	public void setTblPost(TblPost tblPost) {
		this.tblPost = tblPost;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id", nullable = false)
	public TblStore getTblStore() {
		return this.tblStore;
	}

	public void setTblStore(TblStore tblStore) {
		this.tblStore = tblStore;
	}

	@Column(name = "post_status", length = 1)
	public String getPostStatus() {
		return this.postStatus;
	}

	public void setPostStatus(String postStatus) {
		this.postStatus = postStatus;
	}

	@Column(name = "post_remark")
	public String getPostRemark() {
		return this.postRemark;
	}

	public void setPostRemark(String postRemark) {
		this.postRemark = postRemark;
	}

	@Column(name = "updated_by", length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
