package net.slide.pojo;

// Generated Jun 18, 2012 7:42:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblRole generated by hbm2java
 */
@Entity
@Table(name = "tbl_role", schema = "public")
public class TblRole implements java.io.Serializable {

	private int roleId;
	private String roleCd;
	private String roleName;
	private String updatedBy;
	private Date updatedOn;
	private Set<TblUser> tblUsers = new HashSet<TblUser>(0);

	public TblRole() {
	}

	public TblRole(int roleId, String roleCd) {
		this.roleId = roleId;
		this.roleCd = roleCd;
	}

	public TblRole(int roleId, String roleCd, String roleName,
			String updatedBy, Date updatedOn, Set<TblUser> tblUsers) {
		this.roleId = roleId;
		this.roleCd = roleCd;
		this.roleName = roleName;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
		this.tblUsers = tblUsers;
	}

	@Id
	@Column(name = "role_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_cd", nullable = false, length = 15)
	public String getRoleCd() {
		return this.roleCd;
	}

	public void setRoleCd(String roleCd) {
		this.roleCd = roleCd;
	}

	@Column(name = "role_name", length = 50)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "updated_by", length = 25)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_on", length = 35)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblRole")
	public Set<TblUser> getTblUsers() {
		return this.tblUsers;
	}

	public void setTblUsers(Set<TblUser> tblUsers) {
		this.tblUsers = tblUsers;
	}

}
