package net.slide.pojo;

// Generated Jun 18, 2012 7:42:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblUserGrp generated by hbm2java
 */
@Entity
@Table(name = "tbl_user_grp", schema = "public")
public class TblUserGrp implements java.io.Serializable {

	private int groupId;
	private String groupCd;
	private String groupName;
	private String updatedBy;
	private Date updatedDate;

	public TblUserGrp() {
	}

	public TblUserGrp(int groupId, String groupCd, String groupName) {
		this.groupId = groupId;
		this.groupCd = groupCd;
		this.groupName = groupName;
	}

	public TblUserGrp(int groupId, String groupCd, String groupName,
			String updatedBy, Date updatedDate) {
		this.groupId = groupId;
		this.groupCd = groupCd;
		this.groupName = groupName;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "group_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "group_cd", nullable = false, length = 10)
	public String getGroupCd() {
		return this.groupCd;
	}

	public void setGroupCd(String groupCd) {
		this.groupCd = groupCd;
	}

	@Column(name = "group_name", nullable = false, length = 100)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "updated_by", length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
