package net.slide.pojo;

// Generated Jun 6, 2012 12:49:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblArea generated by hbm2java
 */
@Entity
@Table(name = "tbl_area", schema = "public")
public class TblArea implements java.io.Serializable {

	private int areaId;
	private TblBanner tblBanner;
	private TblUser tblUser;
	private String areaCd;
	private String areaName;
	private String areaStatus;
	private Date updatedDate;
	private String updatedBy;
	private Set<TblTaskArea> tblTaskAreas = new HashSet<TblTaskArea>(0);
	private Set<TblChklstAreaDetail> tblChklstAreaDetails = new HashSet<TblChklstAreaDetail>(
			0);
	private Set<TblPostArea> tblPostAreas = new HashSet<TblPostArea>(0);
	private Set<TblChklstArea> tblChklstAreas = new HashSet<TblChklstArea>(0);
	private Set<TblStore> tblStores = new HashSet<TblStore>(0);

	public TblArea() {
	}

	public TblArea(int areaId, TblBanner tblBanner, String areaCd) {
		this.areaId = areaId;
		this.tblBanner = tblBanner;
		this.areaCd = areaCd;
	}

	public TblArea(int areaId, TblBanner tblBanner, TblUser tblUser,
			String areaCd, String areaName, String areaStatus,
			Date updatedDate, String updatedBy, Set<TblTaskArea> tblTaskAreas,
			Set<TblChklstAreaDetail> tblChklstAreaDetails,
			Set<TblPostArea> tblPostAreas, Set<TblChklstArea> tblChklstAreas,
			Set<TblStore> tblStores) {
		this.areaId = areaId;
		this.tblBanner = tblBanner;
		this.tblUser = tblUser;
		this.areaCd = areaCd;
		this.areaName = areaName;
		this.areaStatus = areaStatus;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
		this.tblTaskAreas = tblTaskAreas;
		this.tblChklstAreaDetails = tblChklstAreaDetails;
		this.tblPostAreas = tblPostAreas;
		this.tblChklstAreas = tblChklstAreas;
		this.tblStores = tblStores;
	}

	@Id
	@Column(name = "area_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getAreaId() {
		return this.areaId;
	}

	public void setAreaId(int areaId) {
		this.areaId = areaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "banner_id", nullable = false)
	public TblBanner getTblBanner() {
		return this.tblBanner;
	}

	public void setTblBanner(TblBanner tblBanner) {
		this.tblBanner = tblBanner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "area_manager_id")
	public TblUser getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(TblUser tblUser) {
		this.tblUser = tblUser;
	}

	@Column(name = "area_cd", nullable = false, length = 25)
	public String getAreaCd() {
		return this.areaCd;
	}

	public void setAreaCd(String areaCd) {
		this.areaCd = areaCd;
	}

	@Column(name = "area_name", length = 100)
	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@Column(name = "area_status", length = 1)
	public String getAreaStatus() {
		return this.areaStatus;
	}

	public void setAreaStatus(String areaStatus) {
		this.areaStatus = areaStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "updated_by", length = 20)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblArea")
	public Set<TblTaskArea> getTblTaskAreas() {
		return this.tblTaskAreas;
	}

	public void setTblTaskAreas(Set<TblTaskArea> tblTaskAreas) {
		this.tblTaskAreas = tblTaskAreas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblArea")
	public Set<TblChklstAreaDetail> getTblChklstAreaDetails() {
		return this.tblChklstAreaDetails;
	}

	public void setTblChklstAreaDetails(
			Set<TblChklstAreaDetail> tblChklstAreaDetails) {
		this.tblChklstAreaDetails = tblChklstAreaDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblArea")
	public Set<TblPostArea> getTblPostAreas() {
		return this.tblPostAreas;
	}

	public void setTblPostAreas(Set<TblPostArea> tblPostAreas) {
		this.tblPostAreas = tblPostAreas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblArea")
	public Set<TblChklstArea> getTblChklstAreas() {
		return this.tblChklstAreas;
	}

	public void setTblChklstAreas(Set<TblChklstArea> tblChklstAreas) {
		this.tblChklstAreas = tblChklstAreas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblArea")
	public Set<TblStore> getTblStores() {
		return this.tblStores;
	}

	public void setTblStores(Set<TblStore> tblStores) {
		this.tblStores = tblStores;
	}

}
