package net.slide.pojo;

// Generated Jun 6, 2012 12:49:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblChklstStore generated by hbm2java
 */
@Entity
@Table(name = "tbl_chklst_store", schema = "public")
public class TblChklstStore implements java.io.Serializable {

	private int chklstStoreId;
	private TblChklst tblChklst;
	private TblStore tblStore;
	private String chklstStatus;
	private String chklstRemark;
	private String updatedBy;
	private Date updatedDate;
	private String chklstSite;
	public TblChklstStore() {
	}

	public TblChklstStore(int chklstStoreId, TblChklst tblChklst,
			TblStore tblStore) {
		this.chklstStoreId = chklstStoreId;
		this.tblChklst = tblChklst;
		this.tblStore = tblStore;
	}

	public TblChklstStore(int chklstStoreId, TblChklst tblChklst,
			TblStore tblStore, String chklstStatus, String chklstRemark,
			String updatedBy, Date updatedDate) {
		this.chklstStoreId = chklstStoreId;
		this.tblChklst = tblChklst;
		this.tblStore = tblStore;
		this.chklstStatus = chklstStatus;
		this.chklstRemark = chklstRemark;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "chklst_store_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getChklstStoreId() {
		return this.chklstStoreId;
	}

	public void setChklstStoreId(int chklstStoreId) {
		this.chklstStoreId = chklstStoreId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chklst_id", nullable = false)
	public TblChklst getTblChklst() {
		return this.tblChklst;
	}

	public void setTblChklst(TblChklst tblChklst) {
		this.tblChklst = tblChklst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id", nullable = false)
	public TblStore getTblStore() {
		return this.tblStore;
	}

	public void setTblStore(TblStore tblStore) {
		this.tblStore = tblStore;
	}

	@Column(name = "chklst_status", length = 1)
	public String getChklstStatus() {
		return this.chklstStatus;
	}

	public void setChklstStatus(String chklstStatus) {
		this.chklstStatus = chklstStatus;
	}

	@Column(name = "chklst_remark")
	public String getChklstRemark() {
		return this.chklstRemark;
	}

	public void setChklstRemark(String chklstRemark) {
		this.chklstRemark = chklstRemark;
	}

	@Column(name = "updated_by", length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}
	@Column(name = "chklst_site", length = 1)
	public String getChklstSite() {
		return chklstSite;
	}

	public void setChklstSite(String chklstSite) {
		this.chklstSite = chklstSite;
	}

}
