package net.slide.pojo;

// Generated Jun 8, 2012 11:43:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblDept generated by hbm2java
 */
@Entity
@Table(name = "tbl_dept", schema = "public")
public class TblDept implements java.io.Serializable {

	private int deptId;
	private TblBanner tblBanner;
	private TblChklstGroup tblChklstGroup;
	private TblPostForum tblPostForum;
	private TblTaskPortfolio tblTaskPortfolio;
	private TblUser tblUser;
	private String deptCd;
	private String deptName;
	private String deptStatus;
	private Date updatedDate;
	private String updatedBy;

	public TblDept() {
	}

	public TblDept(int deptId, TblBanner tblBanner, String deptCd) {
		this.deptId = deptId;
		this.tblBanner = tblBanner;
		this.deptCd = deptCd;
	}

	public TblDept(int deptId, TblBanner tblBanner,
			TblChklstGroup tblChklstGroup, TblPostForum tblPostForum,
			TblTaskPortfolio tblTaskPortfolio, TblUser tblUser, String deptCd,
			String deptName, String deptStatus, Date updatedDate,
			String updatedBy) {
		this.deptId = deptId;
		this.tblBanner = tblBanner;
		this.tblChklstGroup = tblChklstGroup;
		this.tblPostForum = tblPostForum;
		this.tblTaskPortfolio = tblTaskPortfolio;
		this.tblUser = tblUser;
		this.deptCd = deptCd;
		this.deptName = deptName;
		this.deptStatus = deptStatus;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	@Id
	@Column(name = "dept_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getDeptId() {
		return this.deptId;
	}

	public void setDeptId(int deptId) {
		this.deptId = deptId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "banner_id", nullable = false)
	public TblBanner getTblBanner() {
		return this.tblBanner;
	}

	public void setTblBanner(TblBanner tblBanner) {
		this.tblBanner = tblBanner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chklist_group_id")
	public TblChklstGroup getTblChklstGroup() {
		return this.tblChklstGroup;
	}

	public void setTblChklstGroup(TblChklstGroup tblChklstGroup) {
		this.tblChklstGroup = tblChklstGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "post_forum_id")
	public TblPostForum getTblPostForum() {
		return this.tblPostForum;
	}

	public void setTblPostForum(TblPostForum tblPostForum) {
		this.tblPostForum = tblPostForum;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "task_portfolio_id")
	public TblTaskPortfolio getTblTaskPortfolio() {
		return this.tblTaskPortfolio;
	}

	public void setTblTaskPortfolio(TblTaskPortfolio tblTaskPortfolio) {
		this.tblTaskPortfolio = tblTaskPortfolio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dept_manager_id")
	public TblUser getTblUser() {
		return this.tblUser;
	}

	public void setTblUser(TblUser tblUser) {
		this.tblUser = tblUser;
	}

	@Column(name = "dept_cd", nullable = false, length = 25)
	public String getDeptCd() {
		return this.deptCd;
	}

	public void setDeptCd(String deptCd) {
		this.deptCd = deptCd;
	}

	@Column(name = "dept_name", length = 100)
	public String getDeptName() {
		return this.deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	@Column(name = "dept_status", length = 1)
	public String getDeptStatus() {
		return this.deptStatus;
	}

	public void setDeptStatus(String deptStatus) {
		this.deptStatus = deptStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "updated_by", length = 20)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
