package net.slide.pojo;

// Generated Jun 18, 2012 7:42:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblPostTopic generated by hbm2java
 */
@Entity
@Table(name = "tbl_post_topic", schema = "public")
public class TblPostTopic implements java.io.Serializable {

	private int id;
	private TblPostForum tblPostForum;
	private String topicName;
	private String topicStatus;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private Set<TblPost> tblPosts = new HashSet<TblPost>(0);

	public TblPostTopic() {
	}

	public TblPostTopic(int id, TblPostForum tblPostForum) {
		this.id = id;
		this.tblPostForum = tblPostForum;
	}

	public TblPostTopic(int id, TblPostForum tblPostForum, String topicName,
			String topicStatus, String createdBy, Date createdDate,
			String updatedBy, Date updatedDate, Set<TblPost> tblPosts) {
		this.id = id;
		this.tblPostForum = tblPostForum;
		this.topicName = topicName;
		this.topicStatus = topicStatus;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.tblPosts = tblPosts;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "forum_id", nullable = false)
	public TblPostForum getTblPostForum() {
		return this.tblPostForum;
	}

	public void setTblPostForum(TblPostForum tblPostForum) {
		this.tblPostForum = tblPostForum;
	}

	@Column(name = "topic_name", length = 100)
	public String getTopicName() {
		return this.topicName;
	}

	public void setTopicName(String topicName) {
		this.topicName = topicName;
	}

	@Column(name = "topic_status", length = 1)
	public String getTopicStatus() {
		return this.topicStatus;
	}

	public void setTopicStatus(String topicStatus) {
		this.topicStatus = topicStatus;
	}

	@Column(name = "created_by", length = 30)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblPostTopic")
	public Set<TblPost> getTblPosts() {
		return this.tblPosts;
	}

	public void setTblPosts(Set<TblPost> tblPosts) {
		this.tblPosts = tblPosts;
	}

}
