package net.slide.pojo;

// Generated Jun 18, 2012 7:42:08 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblSystxno generated by hbm2java
 */
@Entity
@Table(name = "tbl_systxno", schema = "public")
public class TblSystxno implements java.io.Serializable {

	private String txnCd;
	private int txnNo;
	private String txnPrefix;

	public TblSystxno() {
	}

	public TblSystxno(String txnCd, int txnNo) {
		this.txnCd = txnCd;
		this.txnNo = txnNo;
	}

	public TblSystxno(String txnCd, int txnNo, String txnPrefix) {
		this.txnCd = txnCd;
		this.txnNo = txnNo;
		this.txnPrefix = txnPrefix;
	}

	@Id
	@Column(name = "txn_cd", unique = true, nullable = false)
	public String getTxnCd() {
		return this.txnCd;
	}

	public void setTxnCd(String txnCd) {
		this.txnCd = txnCd;
	}

	@Column(name = "txn_no", nullable = false)
	public int getTxnNo() {
		return this.txnNo;
	}

	public void setTxnNo(int txnNo) {
		this.txnNo = txnNo;
	}

	@Column(name = "txn_prefix", length = 10)
	public String getTxnPrefix() {
		return this.txnPrefix;
	}

	public void setTxnPrefix(String txnPrefix) {
		this.txnPrefix = txnPrefix;
	}

}
