package net.slide.pojo;

// Generated Jun 18, 2012 7:42:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblTaskPortfolio generated by hbm2java
 */
@Entity
@Table(name = "tbl_task_portfolio", schema = "public")
public class TblTaskPortfolio implements java.io.Serializable {

	private int portfolioId;
	private String portfolioCd;
	private String portfolioName;
	private String status;
	private String updatedBy;
	private Date updatedDate;
	private Set<TblTask> tblTasks = new HashSet<TblTask>(0);
	private Set<TblDept> tblDepts = new HashSet<TblDept>(0);

	public TblTaskPortfolio() {
	}

	public TblTaskPortfolio(int portfolioId, String portfolioCd) {
		this.portfolioId = portfolioId;
		this.portfolioCd = portfolioCd;
	}

	public TblTaskPortfolio(int portfolioId, String portfolioCd,
			String portfolioName, String status, String updatedBy,
			Date updatedDate, Set<TblTask> tblTasks, Set<TblDept> tblDepts) {
		this.portfolioId = portfolioId;
		this.portfolioCd = portfolioCd;
		this.portfolioName = portfolioName;
		this.status = status;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.tblTasks = tblTasks;
		this.tblDepts = tblDepts;
	}

	@Id
	@Column(name = "portfolio_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public int getPortfolioId() {
		return this.portfolioId;
	}

	public void setPortfolioId(int portfolioId) {
		this.portfolioId = portfolioId;
	}

	@Column(name = "portfolio_cd", nullable = false, length = 25)
	public String getPortfolioCd() {
		return this.portfolioCd;
	}

	public void setPortfolioCd(String portfolioCd) {
		this.portfolioCd = portfolioCd;
	}

	@Column(name = "portfolio_name", length = 100)
	public String getPortfolioName() {
		return this.portfolioName;
	}

	public void setPortfolioName(String portfolioName) {
		this.portfolioName = portfolioName;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "updated_by", length = 30)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblTaskPortfolio")
	public Set<TblTask> getTblTasks() {
		return this.tblTasks;
	}

	public void setTblTasks(Set<TblTask> tblTasks) {
		this.tblTasks = tblTasks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblTaskPortfolio")
	public Set<TblDept> getTblDepts() {
		return this.tblDepts;
	}

	public void setTblDepts(Set<TblDept> tblDepts) {
		this.tblDepts = tblDepts;
	}

}
